extends: default

rules:
  anchors:
    forbid-undeclared-aliases: true
    forbid-duplicated-anchors: true
    forbid-unused-anchors: true
  braces:
    forbid: non-empty
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
    forbid-in-block-sequences: true
  float-values:
    forbid-inf: false
    forbid-nan: false
    forbid-scientific-notation: false
    require-numeral-before-decimal: true
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates:
    forbid-duplicated-merge-keys: false
  line-length:
    max: 256
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
    level: warning
  new-line-at-end-of-file: {}
  new-lines:
    type: unix
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false
  quoted-strings:
    quote-type: double
    required: only-when-needed
    extra-required:
      # Quoting variables like $FOO, ${FOO} or ${{FOO}} is required, since some tools, like k3d, preprocess the YAML files
      # and replace the variables with their values. If the value is not quoted, it sometimes leads to schema validation errors.
      # For example, if the configuration is like `port: ${REGISTRY_PORT}`, it will be replaced with `5000`, and the resulting
      # configuration will be `port: 5000` which type is number, but the schema expects a string like `port: "5000". To prevent
      # this, we should quote every variable for safety. About this regex, see https://regex101.com/r/IblYeC/1
      - \$([a-zA-Z0-9_.]+|{\s*[a-zA-Z0-9_.]+\s*}|{{\s*[a-zA-Z0-9_.]+\s*}})
    extra-allowed: []
    allow-quoted-quotes: true
    check-keys: false
  trailing-spaces: {}
  truthy:
    allowed-values:
      - "true"
      - "false"
    check-keys: false # prevent checking keys since GitHub Actions workflow uses "on" as a key
ignore: |
  node_modules/
  **/charts/*/templates
  **/charts/*/crds
  **/charts/*/Chart.yaml
  **/charts/*/values.yaml
  .moon/docker
